# Generated by Django 6.0.8 on 2026-09-07 15:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExistingModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("status", models.CharField(default="draft", max_length=32)),
                ("secret", models.TextField(default="not in audit")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant", models.CharField(max_length=64)),
                ("value", models.IntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testapp.invoice"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
