# Generated by Django 6.0.8 on 2026-09-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant", models.CharField(max_length=64)),
                ("note", models.CharField(default="", max_length=64)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="testapp.invoice"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
