# Generated by Django 6.0.8 on 2026-09-07 15:45

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_label", models.CharField(max_length=255)),
                ("object_pk", models.CharField(max_length=255)),
                ("scope", models.CharField(max_length=255)),
                ("revision", models.PositiveBigIntegerField(default=0)),
                ("digest", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model_label", "object_pk"), name="psc_resource_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision", models.PositiveBigIntegerField()),
                ("scope", models.CharField(max_length=255)),
                ("actor", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=32)),
                (
                    "before",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
                    ),
                ),
                (
                    "after",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, max_length=255)),
                ("previous_digest", models.CharField(blank=True, max_length=64)),
                ("digest", models.CharField(max_length=64)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="pyscoped.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["revision"],
                "indexes": [
                    models.Index(fields=["scope", "occurred_at"], name="psc_event_scope_time")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "revision"), name="psc_event_revision"
                    )
                ],
            },
        ),
    ]
